Veta\HomeworkBundle\Entity\Info:
    type: entity
    repositoryClass: Veta\HomeworkBundle\Repository\InfoRepository
    table: info
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        text:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
